import streamlit as st
import pandas as pd
import requests
import re
import hashlib
from datetime import date
from io import StringIO

try:
    from fpdf import FPDF
    FPDF_DISPONIBLE = True
except ImportError:
    FPDF_DISPONIBLE = False

try:
    from supabase import create_client
    SUPABASE_DISPONIBLE = True
except ImportError:
    SUPABASE_DISPONIBLE = False

if SUPABASE_DISPONIBLE:
    @st.cache_resource
    def obtener_cliente_supabase():
        return create_client(st.secrets["SUPABASE_URL"], st.secrets["SUPABASE_KEY"])

# CONFIGURACIÓN
st.set_page_config(page_title="MZero Web", layout="wide")

# --- DICCIONARIO DE TRADUCCIONES (IDIOMAS) ---
TEXTOS = {
    "es": {
        "nav_titulo": "Navegación",
        "menu_docs": "Documentos",
        "menu_eval": "Evaluaciones",
        "sesion_iniciada": "Sesión iniciada:",
        "cerrar_sesion": "CERRAR SESIÓN",
        "usuario": "Usuario:",
        "password": "Contraseña:",
        "btn_acceder": "Acceder",
        "error_login": "Usuario o contraseña incorrectos",
        "error_cred": "Error al conectar con la hoja Credenciales",
        "area_docs": "Área de Documentación y Consultas",
        "asoc_colab": "Asociados y Colaboradores",
        "asociados": "Asociados",
        "acceso_asociados": "Acceso Asociados",
        "acceso_colaboradores": "Acceso Colaboradores",
        "acceso_candidatos": "Acceso Candidatos",
        "colaboradores": "Colaboradores",
        "funcionalidad": "Funcionalidad",
        "contacto": "Contacto",
        "como_participar": "Cómo participar",
        "eslogan": "Conectando talento, transformando la industria",
        "aviso_login_eval": "Debes iniciar sesión en el sidebar para acceder al módulo de evaluaciones.",
        "profesor": "Profesor",
        "id_docente": "Id Docente",
        "usuario_docente": "Usuario Docente",
        "acceso_docente": "Acceso Docente",
        "aviso_id_docente": "Introduce tu Id Docente para ver los cursos asignados.",
        "aviso_sin_cursos_docente": "No hay ningún curso asignado a este Id Docente.",
        "curso": "Curso",
        "modulo": "Módulo",
        "nivel_bloque": "Nivel del Bloque",
        "alumno": "Nombre del Alumno",
        "subt_puntuacion": "Puntuación (1=Insuficiente, 3=Suficiente, 5=Excelente)",
        "que_se_mide": "¿Qué se mide aquí?",
        "nivel_rubrica": "Nivel de Rúbrica:",
        "nota_final": "NOTA FINAL",
        "guardar_alumno": "GUARDAR ALUMNO",
        "resumen_alumnos": "Resumen de Alumnos",
        "gestionar_alumnos": "Gestionar alumnos (Eliminar)",
        "enviar_sheets": "ENVIAR TODO A GOOGLE SHEETS",
        "exito_envio": "Enviado con éxito a Google Sheets",
        "modo_edicion": "--- MODO EDICIÓN ---",
        "candidatos": "Candidatos",
        "escribir_peticion": "Escribe tu petición:",
        "enviar": "Enviar",
        "peticion_enviada": "Petición enviada correctamente.",
        "error_peticion": "No se pudo enviar la petición. Inténtalo de nuevo.",
        "campo_vacio_peticion": "Escribe algo antes de enviar.",
        "acceso_concedido": "Acceso concedido:",
        "error_acceso_participar": "Usuario o contraseña incorrectos, o no estás inscrito.",
        "solicitar_alta": "¿Todavía no estás dado de alta? Solicita el registro",
        "enviar_solicitud": "Enviar solicitud",
        "solicitud_enviada": "Solicitud enviada correctamente.",
        "error_solicitud": "No se pudo enviar la solicitud. Inténtalo de nuevo.",
        "campo_vacio_empresa": "Escribe al menos el nombre de la empresa.",
        "campo_nombre_empresa": "Nombre Empresa",
        "campo_nombre_centro": "Nombre del Centro",
        "campo_sector": "Sector",
        "campo_provincia": "Provincia",
        "campo_poblacion": "Población",
        "campo_cp": "CP",
        "campo_razon_social": "Razón Social",
        "campo_cif_nif": "CIF/NIF",
        "campo_telefono": "Teléfono",
        "campo_email": "Email",
        "campo_nombre_contacto": "Nombre Contacto",
        "campo_web": "Web",
        "campo_usuario_deseado": "Usuario que quiero usar",
        "campo_contrasena_deseada": "Contraseña que quiero usar",
        "campo_vacio_usuario_contrasena": "Indica el usuario y la contraseña que quieres usar.",
        "solicitud_pendiente_aviso": "Solicitud enviada. En cuanto sea aprobada podrás acceder con tu usuario y contraseña.",
        "anadir_curso": "Añadir curso",
        "campo_referencia_curso": "Referencia del curso",
        "campo_nombre_curso": "Nombre del curso",
        "campo_nombre_modulo": "Nombre del módulo",
        "campo_horas_totales": "Horas totales del curso",
        "campo_competencias": "Competencias adquiridas",
        "enviar_curso": "Enviar curso",
        "curso_enviado": "Curso enviado. Quedará visible en cuanto lo aprobemos.",
        "campo_vacio_curso": "Rellena al menos la referencia y el nombre del curso.",
        "anadir_docente": "Añadir docente",
        "campo_nombre_docente": "Nombre del docente",
        "campo_curso_relacionado": "Curso al que está relacionado",
        "enviar_docente": "Enviar docente",
        "docente_enviado": "Docente enviado. En cuanto lo activemos, le enviaremos su clave de acceso por email.",
        "campo_vacio_docente": "Rellena el nombre, usuario y email del docente.",
        "sin_cursos_propios": "Primero añade un curso para poder relacionarle un docente.",
        "descargar_pdf": "📄 Descargar PDF antes de enviar",
        "fpdf_no_disponible": "Para poder descargar el PDF, añade 'fpdf2' al archivo requirements.txt de la app.",
        "titulos_func": ["Argumentos M-Zero", "¿Por qué ser Asociado o Colaborador?", "Metodología M0", "El sello M-Zero 'Certificación de calidad'"],
        "campo_nombre_alumno": "Nombre",
        "campo_apellidos_alumno": "Apellidos",
        "campo_localidad": "Localidad",
        "campo_tablas_faltan": "Faltan tablas de gestión de cursos en Supabase: {tablas}.",
        "campo_migracion_cursos": "La conexión actual con SUPABASE_URL y SUPABASE_KEY no cambia. Ejecuta el SQL de migración de cursos para crear estas tablas.",
        "estado_pendiente": "pendiente",
        "estado_activo": "activo",
        "plan_basic": "BASIC",
        "plan_standard": "STANDARD",
        "plan_basic_precio": "50 €/curso",
        "plan_standard_precio": "38 €/mes",
        "plan_promocion": "Promoción 2026",
        "plan_uso_app": "Uso indefinido de la app",
        "plan_basic_uso_app": "Uso por curso",
        "plan_etiqueta_web": "Etiqueta enlace a su web",
        "plan_impuestos": "Impuestos incluidos",
        "plan_standard_inactivo": "De momento no disponible",
        "plan_seleccionar_basic": "Seleccionar BASIC",
        "plan_standard_bloqueado": "STANDARD no disponible",
        "plan_volver": "← Volver a las opciones",
        "reg_plan_seleccionado": "Plan seleccionado: BASIC",
        "plan_subtitulo": "Selecciona una modalidad para continuar con el registro.",
        "asoc_plan_basic_precio": "70 €/informe",
        "asoc_plan_standard_precio": "100 €/mes",
        "asoc_plan_promocion": "PROMOCIÓN",
        "asoc_plan_uso_app": "Uso de la app para peticiones de candidatos o formaciones",
        "asoc_plan_etiqueta_web": "Etiqueta enlace a su web",
        "asoc_plan_informe_max": "Informe máximo de 20 alumnos",
        "asoc_plan_informe_mensual": "Informe mensual de candidatos del sector",
        "asoc_plan_standard_inactivo": "De momento no disponible",
        "asoc_plan_seleccionar_basic": "Seleccionar BASIC",
        "asoc_plan_standard_bloqueado": "STANDARD no disponible",
        "asoc_plan_volver": "← Volver a las opciones",
        "asoc_plan_subtitulo": "Selecciona una modalidad para continuar con el registro.",
        "asoc_reg_plan_seleccionado": "Plan seleccionado: BASIC",
        "gestion_cursos": 'Gestión de cursos',
        "gestion_cursos_desc": 'Crea una nueva edición de un curso, reutiliza la información que ya exista y gestiona posteriormente sus docentes y alumnos.',
        "crear_nuevo_curso": '➕ Crear nuevo curso',
        "mis_cursos": '📚 Mis cursos',
        "selecciona_curso": '1. Selecciona el curso',
        "help_codigo": 'Introduce el código del curso. Si ya existe, se reutilizará su ficha.',
        "curso_existente": '✅ Curso existente encontrado: **{ref} — {nombre}**. Se reutilizará su información y no tendrás que volver a describirlo.',
        "codigo_nuevo_info": 'Si es un código nuevo, completa la ficha del curso.',
        "docentes_edicion": '2. Docentes de esta edición',
        "docentes_reutilizables": 'Estos docentes ya están relacionados con este código de curso. Puedes reutilizarlos sin volver a introducir sus datos.',
        "sin_docentes_curso": 'Este código existe, pero todavía no tiene docentes relacionados.',
        "anadir_docentes_nuevos": 'Añadir docentes nuevos',
        "nombre_docente": 'Nombre del docente',
        "usuario_docente": 'Usuario del docente',
        "email_docente": 'Email del docente',
        "anadir_docente_nuevo": '➕ Añadir docente nuevo a la edición',
        "rellena_docente": 'Rellena nombre, usuario y email del docente.',
        "docentes_tendra": 'Docentes que tendrá esta edición: **{total}**',
        "alumnos_edicion": '3. Alumnos de la nueva edición',
        "alumnos_info": 'Los alumnos pertenecen a cada edición/grupo. Aunque reutilices el mismo código y los mismos docentes, los alumnos de esta nueva edición deben añadirse aquí.',
        "anadir_alumno_edicion": '➕ Añadir alumno a la nueva edición',
        "todos_campos_alumno": 'Todos los campos del alumno son obligatorios.',
        "enviar_peticion_curso": '4. Enviar petición del curso',
        "enviar_peticion_curso_btn": '🚀 ENVIAR PETICIÓN DEL CURSO',
        "indica_codigo": 'Indica el código del curso.',
        "codigo_nuevo_nombre": 'Al ser un código nuevo, debes indicar el nombre del curso.',
        "al_menos_docente": 'Añade o reutiliza al menos un docente para esta edición.',
        "al_menos_alumno": 'Debes añadir al menos un alumno a la nueva edición.',
        "peticion_curso_ok": "Petición del curso enviada correctamente. Puedes consultar y ampliar esta edición desde 'Mis cursos'.",
        "error_peticion_curso": 'No se pudo enviar la petición del curso: {error}',
        "mis_cursos_info": 'Todavía no tienes cursos enviados.',
        "estado": 'Estado:',
        "cerrado": '🔒 CERRADO',
        "abierto": '🟢 ABIERTO',
        "resumen_doc_alu": '{docentes} docentes · {alumnos} alumnos',
        "seccion_docentes": 'Docentes',
        "seccion_alumnos": 'Alumnos',
        "sin_alumnos": 'No hay alumnos registrados.',
        "edicion_abierta": 'Esta edición está abierta. Puedes añadir docentes o alumnos hasta que el docente envíe las evaluaciones.',
        "anadir_docente": 'Añadir docente',
        "usuario": 'Usuario',
        "email": 'Email',
        "docente_anadido": 'Docente añadido a esta edición.',
        "error_anadir_docente": 'No se pudo añadir el docente: {error}',
        "anadir_alumno": 'Añadir alumno',
        "alumno_anadido": 'Alumno añadido a esta edición.',
        "error_anadir_alumno": 'No se pudo añadir el alumno: {error}',
        "edicion_cerrada": '🔒 Esta edición está cerrada porque el docente ya ha enviado las evaluaciones. Ya no se pueden añadir docentes ni alumnos.',
        "codigo_curso_nuevo": 'Si el código ya existe, se reutilizará su ficha.',

    },
    "ca": {
        "nav_titulo": "Navegació",
        "menu_docs": "Documents",
        "menu_eval": "Avaluacions",
        "sesion_iniciada": "Sessió iniciada:",
        "cerrar_sesion": "TANCAR SESSIÓ",
        "usuario": "Usuari:",
        "password": "Contrasenya:",
        "btn_acceder": "Accedir",
        "error_login": "Usuari o contrasenya incorrectes",
        "error_cred": "En connectar amb el full Credencials",
        "area_docs": "Àrea de Documentació i Consultes",
        "asoc_colab": "Associats i Col·laboradors",
        "asociados": "Associats",
        "acceso_asociados": "Accés Associats",
        "acceso_colaboradores": "Accés Col·laboradors",
        "acceso_candidatos": "Accés Candidats",
        "colaboradores": "Col·laboradors",
        "funcionalidad": "Funcionalitat",
        "contacto": "Contacte",
        "como_participar": "Com participar",
        "eslogan": "Connectant talent, transformant la indústria",
        "aviso_login_eval": "Has d'iniciar sessió al sidebar per accedir al mòdul d'avaluacions.",
        "profesor": "Professor",
        "id_docente": "Id Docent",
        "usuario_docente": "Usuari Docent",
        "acceso_docente": "Accés Docent",
        "aviso_id_docente": "Introdueix el teu Id Docent per veure els cursos assignats.",
        "aviso_sin_cursos_docente": "No hi ha cap curs assignat a aquest Id Docent.",
        "curso": "Curs",
        "modulo": "Mòdul",
        "nivel_bloque": "Nivell del Bloc",
        "alumno": "Nom de l'Alumne",
        "subt_puntuacion": "Puntuació (1=Insuficient, 3=Suficient, 5=Excel·lent)",
        "que_se_mide": "Què es mesura aquí?",
        "nivel_rubrica": "Nivell de Rúbrica:",
        "nota_final": "NOTA FINAL",
        "guardar_alumno": "GUARDAR ALUMNE",
        "resumen_alumnos": "Resum d'Alumnes",
        "gestionar_alumnos": "Gestionar alumnes (Eliminar)",
        "enviar_sheets": "ENVIAR TOT A GOOGLE SHEETS",
        "exito_envio": "Enviat amb èxit a Google Sheets",
        "modo_edicion": "--- MODE EDICIÓ ---",
        "candidatos": "Candidats",
        "escribir_peticion": "Escriu la teva petició:",
        "enviar": "Enviar",
        "peticion_enviada": "Petició enviada correctament.",
        "error_peticion": "No s'ha pogut enviar la petició. Torna-ho a provar.",
        "campo_vacio_peticion": "Escriu alguna cosa abans d'enviar.",
        "acceso_concedido": "Accés concedit:",
        "error_acceso_participar": "Usuari o contrasenya incorrectes, o no estàs inscrit.",
        "solicitar_alta": "Encara no estàs donat d'alta? Sol·licita el registre",
        "enviar_solicitud": "Enviar sol·licitud",
        "solicitud_enviada": "Sol·licitud enviada correctament.",
        "error_solicitud": "No s'ha pogut enviar la sol·licitud. Torna-ho a provar.",
        "campo_vacio_empresa": "Escriu com a mínim el nom de l'empresa.",
        "campo_nombre_empresa": "Nom Empresa",
        "campo_nombre_centro": "Nom del Centre",
        "campo_sector": "Sector",
        "campo_provincia": "Província",
        "campo_poblacion": "Població",
        "campo_cp": "CP",
        "campo_razon_social": "Raó Social",
        "campo_cif_nif": "CIF/NIF",
        "campo_telefono": "Telèfon",
        "campo_email": "Email",
        "campo_nombre_contacto": "Nom Contacte",
        "campo_web": "Web",
        "campo_usuario_deseado": "Usuari que vull utilitzar",
        "campo_contrasena_deseada": "Contrasenya que vull utilitzar",
        "campo_vacio_usuario_contrasena": "Indica l'usuari i la contrasenya que vols utilitzar.",
        "solicitud_pendiente_aviso": "Sol·licitud enviada. Quan sigui aprovada podràs accedir amb el teu usuari i contrasenya.",
        "anadir_curso": "Afegir curs",
        "campo_referencia_curso": "Referència del curs",
        "campo_nombre_curso": "Nom del curs",
        "campo_nombre_modulo": "Nom del mòdul",
        "campo_horas_totales": "Hores totals del curs",
        "campo_competencias": "Competències adquirides",
        "enviar_curso": "Enviar curs",
        "curso_enviado": "Curs enviat. Quedarà visible quan l'aprovem.",
        "campo_vacio_curso": "Omple almenys la referència i el nom del curs.",
        "anadir_docente": "Afegir docent",
        "campo_nombre_docente": "Nom del docent",
        "campo_curso_relacionado": "Curs al qual està relacionat",
        "enviar_docente": "Enviar docent",
        "docente_enviado": "Docent enviat. Quan l'activem, li enviarem la seva clau d'accés per email.",
        "campo_vacio_docente": "Omple el nom, usuari i email del docent.",
        "sin_cursos_propios": "Primer afegeix un curs per poder-hi relacionar un docent.",
        "descargar_pdf": "📄 Descarregar PDF abans d'enviar",
        "fpdf_no_disponible": "Per poder descarregar el PDF, afegeix 'fpdf2' a l'arxiu requirements.txt de l'app.",
        "titulos_func": ["Arguments M-Zero", "Per què ser Associat o Colaborador?", "Metodologia M0", "El segell M-Zero 'Certificació de qualitat'"],
        "campo_nombre_alumno": "Nom",
        "campo_apellidos_alumno": "Cognoms",
        "campo_localidad": "Localitat",
        "campo_tablas_faltan": "Falten taules de gestió de cursos a Supabase: {tablas}.",
        "campo_migracion_cursos": "La connexió actual amb SUPABASE_URL i SUPABASE_KEY no canvia. Executa l’SQL de migració de cursos per crear aquestes taules.",
        "estado_pendiente": "pendent",
        "estado_activo": "actiu",
        "plan_basic": "BASIC",
        "plan_standard": "STANDARD",
        "plan_basic_precio": "50 €/curs",
        "plan_standard_precio": "38 €/mes",
        "plan_promocion": "Promoció 2026",
        "plan_uso_app": "Ús indefinit de l'app",
        "plan_basic_uso_app": "Ús per curs",
        "plan_etiqueta_web": "Etiqueta amb enllaç al seu web",
        "plan_impuestos": "Impostos inclosos",
        "plan_standard_inactivo": "De moment no disponible",
        "plan_seleccionar_basic": "Seleccionar BASIC",
        "plan_standard_bloqueado": "STANDARD no disponible",
        "plan_volver": "← Tornar a les opcions",
        "reg_plan_seleccionado": "Pla seleccionat: BASIC",
        "plan_subtitulo": "Selecciona una modalitat per continuar amb el registre.",
        "asoc_plan_basic_precio": "70 €/informe",
        "asoc_plan_standard_precio": "100 €/mes",
        "asoc_plan_promocion": "PROMOCIÓ",
        "asoc_plan_uso_app": "Ús de l'app per a peticions de candidats o formacions",
        "asoc_plan_etiqueta_web": "Etiqueta amb enllaç al seu web",
        "asoc_plan_informe_max": "Informe màxim de 20 alumnes",
        "asoc_plan_informe_mensual": "Informe mensual de candidats del sector",
        "asoc_plan_standard_inactivo": "De moment no disponible",
        "asoc_plan_seleccionar_basic": "Seleccionar BASIC",
        "asoc_plan_standard_bloqueado": "STANDARD no disponible",
        "asoc_plan_volver": "← Tornar a les opcions",
        "asoc_plan_subtitulo": "Selecciona una modalitat per continuar amb el registre.",
        "asoc_reg_plan_seleccionado": "Pla seleccionat: BASIC",
        "gestion_cursos": 'Gestió de cursos',
        "gestion_cursos_desc": 'Crea una nova edició d’un curs, reutilitza la informació que ja existeixi i gestiona posteriorment els seus docents i alumnes.',
        "crear_nuevo_curso": '➕ Crear nou curs',
        "mis_cursos": '📚 Els meus cursos',
        "selecciona_curso": '1. Selecciona el curs',
        "help_codigo": 'Introdueix el codi del curs. Si ja existeix, se’n reutilitzarà la fitxa.',
        "curso_existente": '✅ Curs existent trobat: **{ref} — {nombre}**. Se’n reutilitzarà la informació i no hauràs de tornar a descriure’l.',
        "codigo_nuevo_info": 'Si és un codi nou, completa la fitxa del curs.',
        "docentes_edicion": '2. Docents d’aquesta edició',
        "docentes_reutilizables": 'Aquests docents ja estan relacionats amb aquest codi de curs. Pots reutilitzar-los sense tornar a introduir-ne les dades.',
        "sin_docentes_curso": 'Aquest codi existeix, però encara no té docents relacionats.',
        "anadir_docentes_nuevos": 'Afegir docents nous',
        "nombre_docente": 'Nom del docent',
        "email_docente": 'Email del docent',
        "anadir_docente_nuevo": '➕ Afegir docent nou a l’edició',
        "rellena_docente": 'Omple nom, usuari i email del docent.',
        "docentes_tendra": 'Docents que tindrà aquesta edició: **{total}**',
        "alumnos_edicion": '3. Alumnes de la nova edició',
        "alumnos_info": 'Els alumnes pertanyen a cada edició/grup. Encara que reutilitzis el mateix codi i els mateixos docents, els alumnes d’aquesta nova edició s’han d’afegir aquí.',
        "anadir_alumno_edicion": '➕ Afegir alumne a la nova edició',
        "todos_campos_alumno": 'Tots els camps de l’alumne són obligatoris.',
        "enviar_peticion_curso": '4. Enviar petició del curs',
        "enviar_peticion_curso_btn": '🚀 ENVIAR PETICIÓ DEL CURS',
        "indica_codigo": 'Indica el codi del curs.',
        "codigo_nuevo_nombre": 'En ser un codi nou, has d’indicar el nom del curs.',
        "al_menos_docente": 'Afegeix o reutilitza almenys un docent per a aquesta edició.',
        "al_menos_alumno": 'Has d’afegir almenys un alumne a la nova edició.',
        "peticion_curso_ok": 'Petició del curs enviada correctament. Pots consultar i ampliar aquesta edició des de «Els meus cursos».',
        "error_peticion_curso": 'No s’ha pogut enviar la petició del curs: {error}',
        "mis_cursos_info": 'Encara no tens cursos enviats.',
        "estado": 'Estat:',
        "cerrado": '🔒 TANCAT',
        "abierto": '🟢 OBERT',
        "resumen_doc_alu": '{docentes} docents · {alumnos} alumnes',
        "seccion_docentes": 'Docents',
        "seccion_alumnos": 'Alumnes',
        "sin_alumnos": 'No hi ha alumnes registrats.',
        "edicion_abierta": 'Aquesta edició està oberta. Pots afegir docents o alumnes fins que el docent enviï les avaluacions.',
        "email": 'Email',
        "docente_anadido": 'Docent afegit a aquesta edició.',
        "error_anadir_docente": 'No s’ha pogut afegir el docent: {error}',
        "anadir_alumno": 'Afegir alumne',
        "alumno_anadido": 'Alumne afegit a aquesta edició.',
        "error_anadir_alumno": 'No s’ha pogut afegir l’alumne: {error}',
        "edicion_cerrada": '🔒 Aquesta edició està tancada perquè el docent ja ha enviat les avaluacions. Ja no es poden afegir docents ni alumnes.',
        "codigo_curso_nuevo": 'Si el codi ja existeix, se’n reutilitzarà la fitxa.',

    }
}

# --- TRADUCCIÓN SOLO VISUAL (Català) de campos y criterios de Evaluaciones ---
# No afecta a los datos que se envían al Excel ni a las claves internas
# (Alumno, Curso, "1. Tasa de eficiencia"...); solo se usa para mostrar en
# pantalla (tabla resumen) y en el PDF descargable.
TRADUCCION_EVAL_CA = {
    "Alumno": "Alumne", "Profesor": "Professor", "Usuario": "Usuari",
    "Curso": "Curs", "Modulo": "Mòdul", "Nivel": "Nivell",
    "Nota": "Nota", "Estado": "Estat",
    "1. Tasa de eficiencia": "1. Taxa d'eficiència",
    "2. Precisión geométrica y mecánica": "2. Precisió geomètrica i mecànica",
    "3. Autonomía ejecutiva": "3. Autonomia executiva",
    "4. Índice de mermas": "4. Índex de minves",
    "5. Mantenimiento de utillaje y entorno": "5. Manteniment de l'utillatge i l'entorn",
    "6. Factor de desempeño temporal": "6. Factor d'acompliment temporal",
    "7. Resolución escenarios de prácticas": "7. Resolució d'escenaris de pràctiques",
    "8. Resolución escenarios de averías": "8. Resolució d'escenaris d'avaries",
    "9. Precisión conceptual y terminología": "9. Precisió conceptual i terminologia",
    "10. Seguridad y normativas": "10. Seguretat i normatives",
    "11. Fiabilidad y compromiso operativo": "11. Fiabilitat i compromís operatiu",
    "12. Capacidad de aprendizaje": "12. Capacitat d'aprenentatge",
    "13. Comunicación y respeto al superior": "13. Comunicació i respecte al superior"
}

# --- TRADUCCIÓN SOLO VISUAL (Català) de las categorías de Asociados/Colaboradores ---
# El filtrado sigue comparando contra el texto original en castellano (columna
# Sector/Categoría del Excel); esto solo cambia la etiqueta que se ve en pantalla.
TRADUCCION_CATEGORIAS_CA = {
    "Mecanizado": "Mecanitzat",
    "Climatización": "Climatització",
    "Fontanería": "Fontaneria",
    "Empresas de trabajo temporal": "Empreses de treball temporal",
    "Electricidad": "Electricitat",
    "Obra": "Obra",
    "Electromecánica": "Electromecànica",
    "Renovables": "Renovables",
    "Hidráulica": "Hidràulica",
    "Construcción Mecánica": "Construcció Mecànica",
    "Asociaciones y Gremios": "Associacions i Gremis",
    "Centros de formación": "Centres de formació",
    "Gremios": "Gremis",
    "Asociaciones": "Associacions"
}

# --- LECTURA DE DATOS Y SINCRONIZACIÓN ---
@st.cache_data(ttl=120)
def cargar_catalogo_cursos_y_modulos():
    url_script = "https://script.google.com/macros/s/AKfycbzAfnmO33bANwUsvDRkeMzLjLgLWZeSdzLNduleZ9UYDLEtIqe4YIb-gHSWmJaaFBYY/exec"
    try:
        response = requests.get(url_script, timeout=30)
        if response.status_code == 200:
            try:
                data = response.json()
                if isinstance(data, dict):
                    return data.get("cursos", []), data.get("modulos", [])
            except Exception:
                st.error(f"El script no devolvió un JSON válido. Respuesta recibida: {response.text[:200]}")
    except Exception as e:
        st.error(f"Error de conexión al cargar cursos y módulos: {e}")
    return [], []

@st.cache_data(ttl=600)
def cargar_datos_de_google():
    url_script = "https://script.google.com/macros/s/AKfycbzZDkU6ZfAK1tdy502iEVlQ3j42GWlVBh5DW1_XCD1BxpEI0NZ7Pss3MV0BMGYDikwR/exec"
    resultado = {}
    # Pedimos las dos pestañas (Textos=es, Text=ca) y las fusionamos en un
    # único diccionario. Antes solo se pedía la de castellano (por defecto),
    # así que los títulos en catalán ("Arguments M-Zero", etc.) nunca llegaban.
    for idioma_param in ["es", "ca"]:
        try:
            response = requests.get(url_script, params={"lang": idioma_param}, timeout=30)
            if response.status_code == 200:
                data = response.json()
                if isinstance(data, list):
                    for item in data:
                        t = item.get("Títul") if item.get("Títul") is not None else item.get("Titulo")
                        c = item.get("Contingut") if item.get("Contingut") is not None else item.get("Contenido")
                        if t is not None:
                            resultado[str(t).strip()] = str(c) if c is not None else ""
